version: "3.7"
services:
  centos_ssh:
    image: yuantaixing/centos_ssh_redis_mongo_mysql:1.1
    networks:
      net:
        ipv4_address: 172.18.0.10
    privileged: true
    restart: always
    container_name: "centos_ssh_redis_mongo_mysql"

networks:
  net:
    name: yjsmf
    ipam:
      config:
        - subnet: 172.18.0.0/16


