version: "3.7"
services:
  redis_1:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.51
    command: redis-server --appendonly yes
  redis_2:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.52
    command: redis-server --appendonly yes
  redis_3:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.53
    command: redis-server --appendonly yes
  redis_4:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.54
    command: redis-server --appendonly yes
  redis_5:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.55
    command: redis-server --appendonly yes

  redis_6:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.56
    command: redis-server --appendonly yes

  redis_7:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.57
    command: redis-server --appendonly yes
  redis_8:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.58
    command: redis-server --appendonly yes
  redis_9:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.59
    command: redis-server --appendonly yes
  redis_10:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.60
    command: redis-server --appendonly yes
  redis_11:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.61
    command: redis-server --appendonly yes
  redis_12:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.62
    command: redis-server --appendonly yes
  redis_13:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.63
    command: redis-server --appendonly yes

  redis_14:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.64
    command: redis-server --appendonly yes
  redis_15:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.65
    command: redis-server --appendonly yes

  redis_16:
    image: redis
    networks:
      net:
        ipv4_address: 172.18.0.66
    command: redis-server --appendonly yes

  mysql_1:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.71
  mysql_2:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.72


  mysql_3:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.73
  mysql_4:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.74

  mysql_5:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.75

  mysql_6:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.76

  mysql_7:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.77

  mysql_8:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.78
  mysql_9:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.79

  mysql_10:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.80
  mysql_11:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.81
  mysql_12:
    image: yuantaixing/mysql5_custom:1.0
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      net:
        ipv4_address: 172.18.0.82



  dockerui:
    image: uifd/ui-for-docker
    privileged: true
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  dvwa:
    image: infoslack/dvwa
    environment:
      - MYSQL_PASS="mypass"
    ports:
      - "8000:80"

  requests_test_server:
    image: kennethreitz/httpbin
    ports:
      - "8011:80"
    networks:
      net:
        ipv4_address: 172.18.0.83


networks:
  net:
    name: yjsmf
    ipam:
      config:
        - subnet: 172.18.0.0/16


