version: "3.7"
services:
  bwapp:
    image: raesene/bwapp
    networks:
      net:
        ipv4_address: 172.18.1.1
    ports:
      - "8001:80"

networks:
  net:
    name: yjsmf
    ipam:
      config:
        - subnet: 172.18.0.0/16


