version: "3.7"
services:
  bwapp_1:
    image: raesene/bwapp
    ports:
      - "9001:80"
    networks:
      net:
        ipv4_address: 172.18.1.3


networks:
  net:
    name: yjsmf
    ipam:
      config:
        - subnet: 172.18.0.0/16


