version: "3.7"
services:
  test_env:
    image: yuantaixing/test_env:1.1
    networks:
      net:
        ipv4_address: 172.18.0.8
    ports:
      - "2201:22"
      - "8101-8110:8101-8110"
    volumes:
      - "/root/exploit:/root/exploit"
networks:
  net:
    name: yjsmf
    ipam:
      config:
        - subnet: 172.18.0.0/16