version: "3.7"
services:
  test_env:
    image: yuantaixing/nginx_uwsgi:1.6
    networks:
      net:
        ipv4_address: 172.18.0.6
    ports:
      - "2200:22"
      - "8090-8100:8090-8100"
    volumes:
      - "/root/dockerfiles:/root/dockerfiles"
      - "/root/yjsmf:/root/yjsmf"
networks:
  net:
    name: yjsmf
    ipam:
      config:
        - subnet: 172.18.0.0/16