version: "3.7"
services:
  gitlab:
    image: yuantaixing/gitlab-ce:1.2
    ports:
      - "443:443"
      - "8080:22"  #暴露的端口
      - "80:80"
    restart: always
    container_name: "gitlab"
    volumes:
      - "/etc/gitlab:/etc/gitlab"            #配置文件
      - "/var/log/gitlab:/var/log/gitlab"  # 日志
      - "/var/opt/gitlab:/var/opt/gitlab"  #数据

    networks:
      net:
        ipv4_address: 172.21.0.2



