version: "3.7"
services:
  centos-ssh-1:
    image: centos-ssh-custom-4
    ports:
      - "2200:22"
      - "15264:15264"
      - "8080-8085:8080-8085"
    privileged: true
    volumes:
      - "..:/home/root/space/yjsmf"
    networks:
      - yjsmf-net


  yjsmf_redis-1:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - yjsmf-net


  yjsmf_mysql-1:
    image: mysql:5.7.25
    environment:
      - MYSQL_ROOT_PASSWORD=4833123yuan
    ports:
      - "3306:3306"
    networks:
      - yjsmf-net

  yjsmf_splash:
    image: scrapinghub/splash
    ports:
      - "8050:8050"
    networks:
      - yjsmf-net

networks:
  yjsmf-net:


