version: "3.7"
services:
  tsrc:
    image: xsrc/xsrc:v1.0.1
    ports:
      - "8280:80"
    networks:
      net:
        ipv4_address: 172.18.0.13
    privileged: true
    restart: always

networks:
  net:
    name: yjsmf
    ipam:
      config:
        - subnet: 172.18.0.0/16