version: "3.7"
services:
  test_env:
    image: yuantaixing/debian:1.3
    networks:
      net:
        ipv4_address: 172.18.0.12
    ports:
      - "2203:22"
      - "8111-8120:8111-8120"
    privileged: true
    restart: always
networks:
  net:
    name: yjsmf
    ipam:
      config:
        - subnet: 172.18.0.0/16